# Generated by Django 3.1 on 2020-11-14 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('l_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatedocument',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templatedocument_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatedocument',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templatedocument_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatedocument',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization'),
        ),
        migrations.AddField(
            model_name='templatedocument',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.templatedocument'),
        ),
        migrations.AddField(
            model_name='tariffchange',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tariffchange_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tariffchange',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.contract', verbose_name='Договір'),
        ),
        migrations.AddField(
            model_name='tariffchange',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tariffchange_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tariffchange',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization'),
        ),
        migrations.AddField(
            model_name='tariffchange',
            name='tariff_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.subscription', verbose_name='Тарифний план'),
        ),
        migrations.AddField(
            model_name='subscriptionpricedetails',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptionpricedetails_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionpricedetails',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptionpricedetails_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionpricedetails',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization'),
        ),
        migrations.AddField(
            model_name='subscriptionpricedetails',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.subscriptionpricedetails'),
        ),
        migrations.AddField(
            model_name='subscriptionpricedetails',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.servicetype'),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stageproperty_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='Договір'),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stageproperty_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicetype_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicetype_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization'),
        ),
        migrations.AddField(
            model_name='registerpayment',
            name='act',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.registeract', verbose_name='Акт'),
        ),
        migrations.AddField(
            model_name='registerpayment',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registerpayment_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registerpayment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='Договір'),
        ),
        migrations.AddField(
            model_name='registerpayment',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registerpayment_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registerpayment',
            name='importer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.importpayment', verbose_name='Назва завантаження'),
        ),
        migrations.AddField(
            model_name='registerpayment',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization'),
        ),
        migrations.AddField(
            model_name='registeract',
            name='accrual',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.registeraccrual', verbose_name='Нарахування'),
        ),
        migrations.AddField(
            model_name='registeract',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registeract_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registeract',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='Договір'),
        ),
        migrations.AddField(
            model_name='registeract',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registeract_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registeract',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization'),
        ),
        migrations.AddField(
            model_name='registeraccrual',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registeraccrual_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registeraccrual',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='Договір'),
        ),
        migrations.AddField(
            model_name='registeraccrual',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registeraccrual_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registeraccrual',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization'),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propertytype_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propertytype_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization'),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.propertytype'),
        ),
        migrations.AddField(
            model_name='productpricedetails',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productpricedetails_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productpricedetails',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productpricedetails_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productpricedetails',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization'),
        ),
        migrations.AddField(
            model_name='productpricedetails',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.productpricedetails'),
        ),
        migrations.AddField(
            model_name='productpricedetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.product'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizationtype_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizationtype_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.organizationtype'),
        ),
        migrations.AddField(
            model_name='mainactivity',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mainactivity_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mainactivity',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mainactivity_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mainactivity',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization'),
        ),
        migrations.AddField(
            model_name='mainactivity',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.mainactivity'),
        ),
        migrations.AddField(
            model_name='importpayment',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='importpayment_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importpayment',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='importpayment_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importpayment',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization'),
        ),
        migrations.AddField(
            model_name='historicalstageproperty',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalstageproperty',
            name='contract',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contracts.contract', verbose_name='Договір'),
        ),
        migrations.AddField(
            model_name='historicalstageproperty',
            name='editor',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalstageproperty',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalstageproperty',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='l_core.coreorganization'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='contractor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='l_core.coreorganization', verbose_name='Контрагент'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='editor',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='l_core.coreorganization'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='parent_element',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contracts.contract', verbose_name='Батьківський елемент'),
        ),
        migrations.AddField(
            model_name='coordination',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coordination_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coordination',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='coordination',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coordination_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coordination',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization'),
        ),
        migrations.AddField(
            model_name='contractsubscription',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractsubscription_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractsubscription',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractsubscription',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractsubscription_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractsubscription',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization'),
        ),
        migrations.AddField(
            model_name='contractsubscription',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.subscription'),
        ),
        migrations.AddField(
            model_name='contractproducts',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractproducts_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractproducts',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractproducts',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractproducts_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractproducts',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization'),
        ),
        migrations.AddField(
            model_name='contractproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.product'),
        ),
        migrations.AddField(
            model_name='contractfinance',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractfinance_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractfinance',
            name='contract',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='Договір'),
        ),
        migrations.AddField(
            model_name='contractfinance',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractfinance_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractfinance',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization'),
        ),
        migrations.AddField(
            model_name='contract',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_contractor', to='l_core.coreorganization', verbose_name='Контрагент'),
        ),
        migrations.AddField(
            model_name='contract',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization'),
        ),
        migrations.AddField(
            model_name='contract',
            name='parent_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='Батьківський елемент'),
        ),
        migrations.AddField(
            model_name='accrualsubscription',
            name='accrual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.registeraccrual'),
        ),
        migrations.AddField(
            model_name='accrualsubscription',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accrualsubscription_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accrualsubscription',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accrualsubscription_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accrualsubscription',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization'),
        ),
        migrations.AddField(
            model_name='accrualsubscription',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.subscription'),
        ),
        migrations.AddField(
            model_name='accrualproducts',
            name='accrual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.registeraccrual'),
        ),
        migrations.AddField(
            model_name='accrualproducts',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accrualproducts_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accrualproducts',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accrualproducts_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accrualproducts',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization'),
        ),
        migrations.AddField(
            model_name='accrualproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.product'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionpricedetails',
            unique_together={('code',)},
        ),
        migrations.AlterUniqueTogether(
            name='productpricedetails',
            unique_together={('code',)},
        ),
    ]
