# Generated by Django 3.1 on 2020-11-27 17:07

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('l_core', '0002_auto_20201127_1907'),
        ('atu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0002_auto_20201114_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstageproperty',
            name='author',
        ),
        migrations.RemoveField(
            model_name='historicalstageproperty',
            name='date_add',
        ),
        migrations.RemoveField(
            model_name='historicalstageproperty',
            name='date_edit',
        ),
        migrations.RemoveField(
            model_name='historicalstageproperty',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='historicalstageproperty',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='stageproperty',
            name='author',
        ),
        migrations.RemoveField(
            model_name='stageproperty',
            name='date_add',
        ),
        migrations.RemoveField(
            model_name='stageproperty',
            name='date_edit',
        ),
        migrations.RemoveField(
            model_name='stageproperty',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='stageproperty',
            name='organization',
        ),
        migrations.AddField(
            model_name='historicalstageproperty',
            name='bank',
            field=models.CharField(choices=[('K', 'Комерційний'), ('Б', 'Бюджет')], max_length=1, null=True, verbose_name='Тип банку'),
        ),
        migrations.AddField(
            model_name='historicalstageproperty',
            name='central_office',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Центральний офіс'),
        ),
        migrations.AddField(
            model_name='historicalstageproperty',
            name='district',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='atu.atudistrict', verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='historicalstageproperty',
            name='fax',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Факс'),
        ),
        migrations.AddField(
            model_name='historicalstageproperty',
            name='full_name',
            field=models.TextField(blank=True, null=True, verbose_name='Повна назва організації'),
        ),
        migrations.AddField(
            model_name='historicalstageproperty',
            name='group_organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='l_core.grouporganization', verbose_name='Група компаній'),
        ),
        migrations.AddField(
            model_name='historicalstageproperty',
            name='main_activity_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Основна діяльність (text)'),
        ),
        migrations.AddField(
            model_name='historicalstageproperty',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примітка'),
        ),
        migrations.AddField(
            model_name='historicalstageproperty',
            name='region',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='atu.aturegion', verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='historicalstageproperty',
            name='register_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата державної реєстрації'),
        ),
        migrations.AddField(
            model_name='historicalstageproperty',
            name='sert_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Серія та номер державної реєстрації'),
        ),
        migrations.AddField(
            model_name='historicalstageproperty',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='historicalstageproperty',
            name='status',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='historicalstageproperty',
            name='taxation_method',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Спосіб оподаткування'),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='bank',
            field=models.CharField(choices=[('K', 'Комерційний'), ('Б', 'Бюджет')], max_length=1, null=True, verbose_name='Тип банку'),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='central_office',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Центральний офіс'),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='atu.atudistrict', verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='fax',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Факс'),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='full_name',
            field=models.TextField(blank=True, null=True, verbose_name='Повна назва організації'),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='group_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.grouporganization', verbose_name='Група компаній'),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='main_activity_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Основна діяльність (text)'),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примітка'),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='atu.aturegion', verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='register_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата державної реєстрації'),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='sert_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Серія та номер державної реєстрації'),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='status',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='taxation_method',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Спосіб оподаткування'),
        ),
        migrations.AlterField(
            model_name='accrualproducts',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accrualproducts_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='accrualproducts',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення'),
        ),
        migrations.AlterField(
            model_name='accrualproducts',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни'),
        ),
        migrations.AlterField(
            model_name='accrualproducts',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accrualproducts_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='accrualproducts',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='accrualproducts',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='accrualproducts',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
        migrations.AlterField(
            model_name='accrualsubscription',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accrualsubscription_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='accrualsubscription',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення'),
        ),
        migrations.AlterField(
            model_name='accrualsubscription',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни'),
        ),
        migrations.AlterField(
            model_name='accrualsubscription',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accrualsubscription_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='accrualsubscription',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='accrualsubscription',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='accrualsubscription',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
        migrations.AlterField(
            model_name='contractfinance',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractfinance_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='contractfinance',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення'),
        ),
        migrations.AlterField(
            model_name='contractfinance',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни'),
        ),
        migrations.AlterField(
            model_name='contractfinance',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractfinance_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='contractfinance',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='contractfinance',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='contractfinance',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
        migrations.AlterField(
            model_name='contractproducts',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractproducts_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='contractproducts',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення'),
        ),
        migrations.AlterField(
            model_name='contractproducts',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни'),
        ),
        migrations.AlterField(
            model_name='contractproducts',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractproducts_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='contractproducts',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='contractproducts',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='contractproducts',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
        migrations.AlterField(
            model_name='contractsubscription',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractsubscription_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='contractsubscription',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення'),
        ),
        migrations.AlterField(
            model_name='contractsubscription',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни'),
        ),
        migrations.AlterField(
            model_name='contractsubscription',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractsubscription_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='contractsubscription',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='contractsubscription',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='contractsubscription',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
        migrations.AlterField(
            model_name='coordination',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coordination_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='coordination',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення'),
        ),
        migrations.AlterField(
            model_name='coordination',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни'),
        ),
        migrations.AlterField(
            model_name='coordination',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coordination_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='coordination',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='coordination',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='coordination',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='date_add',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='**Дата створення'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='date_edit',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='**Дата останньої зміни'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='editor',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
        migrations.AlterField(
            model_name='historicalstageproperty',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='historicalstageproperty',
            name='edrpou',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='ЄДРПОУ'),
        ),
        migrations.AlterField(
            model_name='historicalstageproperty',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='EMAIL'),
        ),
        migrations.AlterField(
            model_name='historicalstageproperty',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='historicalstageproperty',
            name='name',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Назва організації'),
        ),
        migrations.AlterField(
            model_name='historicalstageproperty',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='historicalstageproperty',
            name='statute_copy',
            field=models.TextField(max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg'])], verbose_name='Статутні документи'),
        ),
        migrations.AlterField(
            model_name='historicalstageproperty',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
        migrations.AlterField(
            model_name='importpayment',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='importpayment_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='importpayment',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення'),
        ),
        migrations.AlterField(
            model_name='importpayment',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни'),
        ),
        migrations.AlterField(
            model_name='importpayment',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='importpayment_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='importpayment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='importpayment',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='importpayment',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
        migrations.AlterField(
            model_name='mainactivity',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mainactivity_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='mainactivity',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення'),
        ),
        migrations.AlterField(
            model_name='mainactivity',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни'),
        ),
        migrations.AlterField(
            model_name='mainactivity',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mainactivity_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='mainactivity',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='mainactivity',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='mainactivity',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizationtype_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення'),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни'),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizationtype_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни'),
        ),
        migrations.AlterField(
            model_name='product',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
        migrations.AlterField(
            model_name='productpricedetails',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productpricedetails_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='productpricedetails',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення'),
        ),
        migrations.AlterField(
            model_name='productpricedetails',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни'),
        ),
        migrations.AlterField(
            model_name='productpricedetails',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productpricedetails_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='productpricedetails',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='productpricedetails',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='productpricedetails',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propertytype_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propertytype_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
        migrations.AlterField(
            model_name='registeraccrual',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registeraccrual_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='registeraccrual',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення'),
        ),
        migrations.AlterField(
            model_name='registeraccrual',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни'),
        ),
        migrations.AlterField(
            model_name='registeraccrual',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registeraccrual_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='registeraccrual',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='registeraccrual',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='registeraccrual',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
        migrations.AlterField(
            model_name='registeract',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registeract_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='registeract',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення'),
        ),
        migrations.AlterField(
            model_name='registeract',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни'),
        ),
        migrations.AlterField(
            model_name='registeract',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registeract_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='registeract',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='registeract',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='registeract',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
        migrations.AlterField(
            model_name='registerpayment',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registerpayment_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='registerpayment',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення'),
        ),
        migrations.AlterField(
            model_name='registerpayment',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни'),
        ),
        migrations.AlterField(
            model_name='registerpayment',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registerpayment_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='registerpayment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='registerpayment',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='registerpayment',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicetype_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicetype_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
        migrations.AlterField(
            model_name='stageproperty',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='stageproperty',
            name='edrpou',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='ЄДРПОУ'),
        ),
        migrations.AlterField(
            model_name='stageproperty',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='EMAIL'),
        ),
        migrations.AlterField(
            model_name='stageproperty',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='stageproperty',
            name='name',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Назва організації'),
        ),
        migrations.AlterField(
            model_name='stageproperty',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='stageproperty',
            name='statute_copy',
            field=models.FileField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg'])], verbose_name='Статутні документи'),
        ),
        migrations.AlterField(
            model_name='stageproperty',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
        migrations.AlterField(
            model_name='subscriptionpricedetails',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptionpricedetails_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='subscriptionpricedetails',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення'),
        ),
        migrations.AlterField(
            model_name='subscriptionpricedetails',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни'),
        ),
        migrations.AlterField(
            model_name='subscriptionpricedetails',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptionpricedetails_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='subscriptionpricedetails',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='subscriptionpricedetails',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='subscriptionpricedetails',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
        migrations.AlterField(
            model_name='tariffchange',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tariffchange_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='tariffchange',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення'),
        ),
        migrations.AlterField(
            model_name='tariffchange',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни'),
        ),
        migrations.AlterField(
            model_name='tariffchange',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tariffchange_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='tariffchange',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='tariffchange',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='tariffchange',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
        migrations.AlterField(
            model_name='templatedocument',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templatedocument_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='templatedocument',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення'),
        ),
        migrations.AlterField(
            model_name='templatedocument',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни'),
        ),
        migrations.AlterField(
            model_name='templatedocument',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templatedocument_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='templatedocument',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='templatedocument',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='templatedocument',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
    ]
