# Generated by Django 3.1 on 2020-11-28 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('l_core', '0002_auto_20201127_1907'),
        ('contracts', '0003_auto_20201127_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstageproperty',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AddField(
            model_name='historicalstageproperty',
            name='date_add',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='**Дата створення'),
        ),
        migrations.AddField(
            model_name='historicalstageproperty',
            name='date_edit',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='**Дата останньої зміни'),
        ),
        migrations.AddField(
            model_name='historicalstageproperty',
            name='editor',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AddField(
            model_name='historicalstageproperty',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stageproperty_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення'),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни'),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stageproperty_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AddField(
            model_name='stageproperty',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
    ]
