# Generated by Django 3.1 on 2020-11-30 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATURegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Область')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Області',
            },
        ),
        migrations.CreateModel(
            name='ATUDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Район')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atu_region_atudistrict', to='atu.aturegion', verbose_name='Область')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Райони',
            },
        ),
    ]
