# Generated by Django 3.1 on 2020-12-02 07:34

import apps.dict_register.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l_core', '0001_initial'),
        ('dict_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainactivity',
            name='protected',
            field=models.BooleanField(default=False, verbose_name='Захищено від видалення'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='protected',
            field=models.BooleanField(default=False, verbose_name='Захищено від видалення'),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='protected',
            field=models.BooleanField(default=False, verbose_name='Захищено від видалення'),
        ),
        migrations.AddField(
            model_name='templatedocument',
            name='protected',
            field=models.BooleanField(default=False, verbose_name='Захищено від видалення'),
        ),
        migrations.AlterField(
            model_name='mainactivity',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.CASCADE, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.CASCADE, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.CASCADE, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='templatedocument',
            name='organization',
            field=models.ForeignKey(help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.CASCADE, to='l_core.coreorganization', verbose_name='**Організація'),
        ),
        migrations.AlterField(
            model_name='templatedocument',
            name='template_file',
            field=models.FileField(null=True, upload_to=apps.dict_register.models.get_upload_template_path, verbose_name='Шаблон документу'),
        ),
    ]
