# Generated by Django 3.1 on 2020-12-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict_register', '0004_auto_20201202_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatedocument',
            options={'verbose_name': 'Шаблон документу', 'verbose_name_plural': 'Шаблони документів'},
        ),
        migrations.AlterField(
            model_name='templatedocument',
            name='related_model_name',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Сигнатура шаблону'),
        ),
    ]
