# Generated by Django 3.1 on 2020-11-27 17:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('l_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreorganization',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='coreorganization',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='department',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
        migrations.AlterField(
            model_name='grouporganization',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?'),
        ),
        migrations.AlterField(
            model_name='grouporganization',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен'),
        ),
    ]
