# Generated by Django 3.1 on 2020-11-29 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('l_core', '0002_auto_20201127_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFormSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('REGISTRATOR', 'Реєстратор'), ('EXECUTOR', 'Виконавець')], max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('form_name', models.CharField(max_length=250)),
            ],
            options={
                'unique_together': {('role', 'active', 'form_name')},
            },
        ),
        migrations.CreateModel(
            name='ClientFormElementSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('client_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='l_core.clientformsettings')),
                ('permissions', models.ManyToManyField(to='auth.Permission')),
            ],
            options={
                'unique_together': {('client_form', 'name')},
            },
        ),
    ]
