# Generated by Django 3.1 on 2020-11-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l_core', '0003_clientformelementsettings_clientformsettings'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientformsettings',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='ClientFormElementSettings',
        ),
        migrations.DeleteModel(
            name='ClientFormSettings',
        ),
    ]
