# Generated by Django 3.1 on 2020-11-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20201114_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaskexecutor',
            name='sign_file',
            field=models.TextField(max_length=100, null=True, verbose_name='Цифровий підпис(файл)'),
        ),
        migrations.AddField(
            model_name='taskexecutor',
            name='sign_file',
            field=models.FileField(null=True, upload_to='', verbose_name='Цифровий підпис(файл)'),
        ),
        migrations.AlterField(
            model_name='basedocument',
            name='mailing_method',
            field=models.CharField(choices=[('EMAIL', 'Електронна пошта'), ('SEV', 'СЕВОВВ'), ('LETTER', 'Поштою (просте)'), ('REGISTERED_LETTER', 'Поштою (рекомендоване)'), ('HAND_OUT', 'Наручно')], default='LETTER', max_length=50, verbose_name='Спосіб відпралення'),
        ),
        migrations.AlterField(
            model_name='basedocument',
            name='source',
            field=models.CharField(choices=[('EMAIL', 'Електронна пошта'), ('SEV', 'СЕВОВВ'), ('LETTER', 'Поштою (просте)'), ('REGISTERED_LETTER', 'Поштою (рекомендоване)'), ('HAND_OUT', 'Наручно')], default='LETTER', max_length=50, verbose_name='Джерело надходження'),
        ),
        migrations.AlterField(
            model_name='historicalbasedocument',
            name='mailing_method',
            field=models.CharField(choices=[('EMAIL', 'Електронна пошта'), ('SEV', 'СЕВОВВ'), ('LETTER', 'Поштою (просте)'), ('REGISTERED_LETTER', 'Поштою (рекомендоване)'), ('HAND_OUT', 'Наручно')], default='LETTER', max_length=50, verbose_name='Спосіб відпралення'),
        ),
        migrations.AlterField(
            model_name='historicalbasedocument',
            name='source',
            field=models.CharField(choices=[('EMAIL', 'Електронна пошта'), ('SEV', 'СЕВОВВ'), ('LETTER', 'Поштою (просте)'), ('REGISTERED_LETTER', 'Поштою (рекомендоване)'), ('HAND_OUT', 'Наручно')], default='LETTER', max_length=50, verbose_name='Джерело надходження'),
        ),
        migrations.AlterField(
            model_name='registrationjournal',
            name='current_max_number',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Поточний максимальний номер'),
        ),
    ]
