# Generated by Django 3.1 on 2020-11-23 19:35

import apps.l_core.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('l_core', '0001_initial'),
        ('document', '0003_auto_20201121_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnerDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_uuid', models.UUIDField(default=uuid.uuid4)),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_edit', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('name', models.CharField(max_length=200, verbose_name='Тип внутрішнього документа')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='innerdocumenttype_author', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='innerdocumenttype_editor', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l_core.coreorganization')),
            ],
            options={
                'verbose_name': 'Тип внутрішнього документу',
                'verbose_name_plural': 'Типи внутрішніх документів',
            },
            bases=(apps.l_core.mixins.CheckProtected, apps.l_core.mixins.RelatedObjects, models.Model),
        ),
        migrations.AddField(
            model_name='basedocument',
            name='inner_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='document.innerdocumenttype', verbose_name='Тип внутрішнього документа'),
        ),
        migrations.AddField(
            model_name='historicalbasedocument',
            name='inner_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='document.innerdocumenttype', verbose_name='Тип внутрішнього документа'),
        ),
    ]
