# Generated by Django 3.1 on 2020-11-30 18:50

import apps.sevovvintegration.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('l_core', '0001_initial'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEVOutgoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True, verbose_name='**Дата створення')),
                ('xml_file', models.FileField(null=True, upload_to=apps.sevovvintegration.models.get_outgoing_xml_file_path)),
                ('message_id', models.CharField(default=uuid.uuid4, max_length=256)),
                ('sending_result', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='document.basedocument')),
                ('from_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_from', to='l_core.coreorganization')),
                ('sign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='document.sign')),
                ('to_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_to', to='l_core.coreorganization')),
            ],
        ),
        migrations.CreateModel(
            name='SEVIncoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True, null=True, verbose_name='**Дата створення')),
                ('xml_file', models.FileField(upload_to=apps.sevovvintegration.models.get_incoming_xml_file_path)),
                ('status', models.CharField(max_length=50)),
                ('from_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_from', to='l_core.coreorganization')),
                ('to_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_to', to='l_core.coreorganization')),
            ],
        ),
    ]
