# Generated by Django 3.1 on 2020-11-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevovvintegration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sevincoming',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='**Дата створення'),
        ),
        migrations.AddField(
            model_name='sevoutgoing',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='**Дата створення'),
        ),
    ]
